### ISSUE TITLE
bannedlist

### ISSUE THREAD

**Issue by a9-wolf** [dawalters1/Wolf.Net#32]
this is a suggestion to create a banned list so bot wont listen to any message by any user in the list. just like phrases loading.

**Comment by dawalters1** [comment]
Install-Package Wolf.Net -Version 4.2.5

Banned list functions exactly like the Authorization handling

To add a user use: Bot.Ban(ids);
To remove a user use: Bot.Unban(ids)
To see if a user is banned use: Bot.IsBanned(id)
To get the list of all banned users use: Bot.Banned

All users added to the banned list will no longer have their messages processed
