### ISSUE TITLE
"Clean" Arabic words to ensure the bot handles each possible letter

### ISSUE THREAD

**Issue by a9-wolf** [dawalters1/Wolf.Net#6]
hey.
this is request if possible. replace the Arabic letter (ه) on the end of the string to (ة). and the letter (أ) on the start of the string to (ا).

**Comment by dewwalters** [comment]
This will be implemented in Version 4.0, but will look into supporting it into Version 3.1.0

**Comment by dawalters1** [comment]
So implemented a variation of this in 4.1.3 Install-Package Wolf.Net -Version 4.1.3

message.Content.CleanString()/Command.Arguement.CleanString() will replace  ```  أَإأ ``` with  ا and ه with ة throughout the entire string, this *should* not effect commands as the command handler will also handle checks for this

If anything has been missed you can do Public.CleanStringMap.Add(toReplace, replaceWith); to add more characters to be replaced
